# Generated by Django 4.1.7 on 2023-03-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_img_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/uploads/'),
        ),
    ]
