# Generated by Django 4.1.7 on 2023-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
