# Generated by Django 4.1.7 on 2023-03-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='products.tag'),
        ),
    ]
