# Generated by Django 4.1.7 on 2023-03-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_categories_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Jewellery', 'Jewellery')], max_length=200, null=True),
        ),
    ]
