# Generated by Django 4.1.7 on 2023-03-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_categories_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
